### PR TITLE
Change .gitignore to ignore love files instead of object files.

### PR DESCRIPTION
**Pull request by account3r2**
We are not using C.

### CODE REVIEW

**Comment by account3r2** [comment]
The reverse fade code can definitely be improved, I'm sure, but I'm leaving that code up to @JoshuaBrockschmidt if he wishes to improve it.

**Comment by jcbrockschmidt** [comment]
Oh, I didn't even know I had a .gitignore.

**Comment by jcbrockschmidt** [comment]
Not sure if you're accounting for a player trying to switch the fade state in the middle of a fading in or fading out. I'll merge it, though.

**Comment by account3r2** [comment]
@JoshuaBrockschmidt Nope. It looks very strange when user spams Esc. Shhh let's not talk about that.

**Comment by jcbrockschmidt** [comment]
@account3r2 I recall I fixed the strange switching in one of my commits preceding this one. I'll have to double check.

**Pull request merged**
